name: ci
on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Haskell Toolchain
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 8.10.4
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
          stack-setup-ghc: true

      - name: Cache stack directories
        uses: actions/cache@v2.1.3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-8.10.4-stack

      - name: Install Dependencies
        run: stack build --only-dependencies

      - name: Build
        run: stack build
