name: ci
on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Haskell Toolchain
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true

      - if: matrix.os == 'windows-latest'
        shell: bash
        run: echo "STACK_DIR=%LOCALAPPDATA%\Programs\stack" >> $GITHUB_ENV

      - if: matrix.os != 'windows-latest'
        shell: bash
        run: echo "STACK_DIR=~/.stack" >> $GITHUB_ENV

      - name: Get Stack Root
        run: echo ${{ env.STACK_DIR }}

      - name: Cache stack directories
        uses: actions/cache@v2.1.3
        with:
          path: ${{ env.STACK_DIR }}
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}

      - name: Install Dependencies
        run: stack build --only-dependencies

      - name: Build
        run: stack build
